Unit tests/date holidays
MahaKHARRAT/date-holidays pull request #9
Opened 2024-12-26 09:05 UTC by faridkhouda

https://planity.atlassian.net/browse/PLAN-15667

2024-12-27 13:36 UTC, tonytang-planity commented
Je pense pas que ça fasse ce que j'attends parce que tu utilises des mocks.
Je voudrai que tu teste la fonctione qui permet de récupérer les jours fériés pour les pays qu'on utilise et vérifier que ça retourne les véritables dates.
Par exemple, pour FR, il faut que ça retourne le 25 décembre, le 1er janvicer, etc.

Pareil pour les autres country code.

2024-12-27 14:40 UTC, faridkhouda commented
> Je pense pas que ça fasse ce que j'attends parce que tu utilises des mocks. Je voudrai que tu teste la fonctione qui permet de récupérer les jours fériés pour les pays qu'on utilise et vérifier que ça retourne les véritables dates. Par exemple, pour FR, il faut que ça retourne le 25 décembre, le 1er janvicer, etc.
> 
> Pareil pour les autres country code.

Si j'ai bien compris  tu veux que je focus sur la function `getHolidays(year?: string | number | Date, lang?: string): HolidaysTypes.Holiday[] ?` Par exemple, vérifier qu’elle retourne les correct public holidays comme le 1er janvier pour FR ? 
Concernant le date format, vu que c’est handled côté app, Est-ce que je dois uniquement valider les valeurs brutes retournées par getHolidays, ou bien vérifier que le format attendu est respecté ?

2024-12-27 15:19 UTC, tonytang-planity commented
Yes c'est ça. Pas besoin de valider le format de la date

2025-01-06 17:19 UTC, faridkhouda commented
⚠️ Some public holidays still need verification as their dates differ between Year+1 and Year+2.
🛠️ Tests for the German language (DE) are still in progress.

2025-01-07 09:38 UTC, MalouPro requested changes

2025-01-07 09:38 UTC, MalouPro commented on package.json
> +    "sinon": "^19.0.2",
tu n'as plus besoin de sinon

2025-01-07 09:38 UTC, MalouPro commented on .github/workflows/ci.yml
> +        node-version: '16'
pour etre cohenrent avec les autre apps de planity: 

node-version: '18'

2025-01-07 09:38 UTC, MalouPro commented on .github/workflows/ci.yml
> +      uses: actions/checkout@v3
tu peux utiliser v4 comme sur les autre github actions de planity stp ?

2025-01-07 09:38 UTC, MalouPro commented on .github/workflows/ci.yml
>        uses: actions/setup-node@v3
meme remarque utilise v4

2025-01-08 17:43 UTC, faridkhouda commented on package.json
> +    "sinon": "^19.0.2",
Done

2025-01-08 17:43 UTC, faridkhouda commented on .github/workflows/ci.yml
> +      uses: actions/checkout@v3
Done

2025-01-08 17:43 UTC, faridkhouda commented on .github/workflows/ci.yml
>        uses: actions/setup-node@v3
Done

2025-01-09 10:06 UTC, merged